# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Project')),
                ('file', models.ImageField(upload_to='pictures', verbose_name='File')),
                ('height', models.IntegerField(blank=True, default=0, null=True, verbose_name='Height')),
                ('width', models.IntegerField(blank=True, default=0, null=True, verbose_name='Height')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Project')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_projects', to='main.Picture')),
                ('thumbnail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_projects', to='main.Picture')),
            ],
        ),
    ]
