# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='size',
            field=models.CharField(choices=[('x-large', 'x-large'), ('large', 'large'), ('medium', 'mediun'), ('small', 'small')], default='small', max_length=10, verbose_name='Size'),
        ),
    ]
